baseURL: http://hues.mpilosov.com
languageCode: en-us
title: Hues of Intelligence
theme: PaperMod
copyright: "Michael Pilosov"

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics:

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Hues of Intelligence
  description: ""
  keywords: [Art, Mathematics, Computation, Artificial Intelligence, Machine Learning]
  # author: ["Michael Pilosov"]
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "2006-01-02"
  defaultTheme: light # dark, light
  disableThemeToggle: false
  ShowReadingTime: false
  ShowShareButtons: true  # global override of disableShare
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShareButtons: ["linkedin", "reddit"]
  ShowRssButtonInSectionTermList: true
  UseHugoToc: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: true
  hideSummary: true
  searchHidden: false
  showtoc: false
  tocopen: false
  editPost:
      URL: "https://github.com/mpilosov/hues/tree/main/content"
      Text: "Suggest Changes" # edit text
      appendFilePath: true # to append file path to Edit link
  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "https://data.math.computer/hsv128.ico"
    favicon16x16: "https://data.math.computer/hsv16.ico"
    favicon32x32:  "https://data.math.computer/hsv32.ico"
    apple_touch_icon: "https://data.math.computer/hsv_sm.png"
    safari_pinned_tab: "https://data.math.computer/hsv_sm.png"

  label:
    text: "Hues of Intelligence"
    # icon: /apple-touch-icon.png
    iconHeight: 35
  ######################################################
  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Hues of Intelligence"
    subtitle: ""
    imageUrl: "https://data.math.computer/hsv_sm.png"
    imageWidth: 200
    imageHeight: 200
    # imageTitle: profile-pic
    buttons:
      - name: About
        url: about
      - name: Gallery
        url: gallery

  ######################################################

  # home-info mode
  homeInfoParams:
    Title: "Hues of Intelligence"
    Content: "Can Machines Discover the Rainbow?"

  ######################################################
  socialIcons:
    - name: gitea
      url: "https://git.mlden.com/mm/colors.git"
    #- name: instagram
    #  url: "https://instagram.com/calculatedcanvas/"
    - name: email
      url: "/contact"
    - name: linkedin
      url: "https://linkedin.com/in/mathematicalmichael"
  ######################################################
  
  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # global editing option
  # editPost:
  #  URL: "https://github.com/<path_to_repo>/content"
  #  Text: "Suggest Changes" # edit text
  #  appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
  
######################################################
menu:
  main:
    #- identifier: search
    #  name: ":mag:"
    #  url: /search/
    #  weight: 100
    #- identifier: docs
    #  name: "docs"
    #  url: /docs/
    #  weight: 40
    - identifier: gallery
      name: "gallery"
      url: /gallery/
      weight: 10
    - identifier: about
      name: "about"
      url: /about/
      weight: 5
######################################################

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

privacy:
  youtube:
    disable: false
    privacyEnhanced: true
